### ISSUE TITLE
Do builds with this crossfile honor LDFLAGS ?

### ISSUE THREAD

**Issue by LW-archlinux** [Oxalin/meson-cross-x86-linux-gnu#2]
A while ago I and other arch linux users looked into meson lib32-* builds for mesa [1].

In post #14 progandy commented that meson crossbuilds don't honor the LDFLAGS env variable.
He expected that to make the crossbuild use LDFLAGS , CFLAGS and CPPFLAGS values at buildtime the contents of those vars would have to be copied completely into the properties section of the crossfile .
We didn't investigate crossbuilding further but settled on a simpler method using meson --native files with  a normal build.

Have you tested whether this crossbuild file honors the arch linux env vars set by makepkg.conf ?

[1] https://bbs.archlinux.org/viewtopic.php?id=241990

**Comment by fafryd1125** [comment]
https://github.com/mesonbuild/meson/issues/4694

**Comment by Oxalin** [comment]
I did not test it, but I could have a look.

**Comment by Ericson2314** [comment]
In https://github.com/mesonbuild/meson/issues/3969 I propose they should; I will make a PR implanting what I propose in that issue soon.

**Comment by Oxalin** [comment]
Answer: no. Sorry for the long delay, it went out of my mind.

**Comment by Ericson2314** [comment]
Meson does respect `LDFLAGS_FOR_BUILD` but not `LDFLAGS` in cross builds at the moment. But in https://github.com/mesonbuild/meson/pull/6827 I make a tiny change so it respects both. You might be interested in that. We already use it in Nixpkgs to help with our distro-wide cross compilation.
